POST http://localhost:3001/client
Content-Type: application/json

{
"name":"Armando",
"lastname":"dfdf",
"passwordHash":"dsfsdfs",
"dni":"sdfsdf",
"email":"sdfsdf",
"phone_number": "sdfsf",
"status":"disabled"
}